"""
Train the Kangaroo adapter for Qwen2.5-VL self-speculative decoding.
"""

import argparse
import json
import os
from typing import Any, Dict, List

import torch
import torch.nn as nn
import torch.nn.functional as F
from accelerate import Accelerator, DistributedDataParallelKwargs
from accelerate.utils import set_seed
from torch import optim
from torch.utils.data import DataLoader, Dataset
from tqdm import tqdm
from transformers import AutoConfig, get_linear_schedule_with_warmup

from adapter import AdapterModel, create_adapter_config, init_adapter_from_base_layer


def parse_args():
    parser = argparse.ArgumentParser(description="Train Kangaroo adapter for Qwen2.5-VL")
    parser.add_argument("--basepath", type=str, default="/data/wangzhichao/projects/MMDuet2/ckpt/MMDuet2_ckpt")
    parser.add_argument("--datadir", type=str, required=True, default="/data/wangzhichao/projects/SSD_RE/datasets/training_data/20_no_reply")
    parser.add_argument("--outdir", type=str, required=True, default="/data/wangzhichao/projects/SSD_full_history/adapter_checkpoints/20_no_reply")
    parser.add_argument("--exit_layer", type=int, default=4)
    parser.add_argument("--num_adapter_layers", type=int, default=3,
                        help="Number of stacked decoder layers in the adapter (TwigVLM-style).")
    parser.add_argument("--lr", type=float, default=1e-5)
    parser.add_argument("--bs", type=int, default=1)
    parser.add_argument("--gradient_accumulation_steps", type=int, default=32)
    parser.add_argument("--num_epochs", type=int, default=20)
    parser.add_argument("--num_warmup_steps", type=int, default=2000)
    parser.add_argument("--total_steps", type=int, default=0,
                        help="Total optimizer steps. Set <=0 to auto-compute from dataloader and epochs.")
    parser.add_argument("--grad_clip", type=float, default=0.5)
    parser.add_argument("--start_epoch", type=int, default=0)
    parser.add_argument("--save_freq", type=int, default=1)
    parser.add_argument("--log_steps", type=int, default=10)
    parser.add_argument("--disable_adapter_mlp", action="store_true",
                        help="Disable the adapter MLP block and keep an attention-only adapter.")
    parser.add_argument("--resume_adapter", type=str, default=None,
                        help="Path to pretrained adapter_model.bin to continue training from")
    parser.add_argument("--kl_temperature", type=float, default=1.0,
                        help="Temperature for KL distribution matching. 1.0 fits the teacher distribution directly.")
    parser.add_argument("--kl_weight", type=float, default=1.0,
                        help="Weight for the KL distribution-matching loss. "
                             "Set to 0 to disable KL entirely (recommended for pure-text warm-up: "
                             "use teacher-argmax CE only via --prefix_ce_tokens 9999 --kl_weight 0).")
    parser.add_argument("--prefix_ce_tokens", type=int, default=1,
                        help="Number of leading supervised tokens to train with teacher-argmax CE. "
                             "Set to a large number (e.g. 9999) to apply CE on ALL supervised "
                             "positions (turns CE into a full LM-style loss).")
    parser.add_argument("--prefix_ce_weight", type=float, default=1.0,
                        help="Weight for the weighted prefix CE term.")
    parser.add_argument("--ce_target", type=str, default="teacher",
                        choices=["teacher", "gt"],
                        help="CE label source. 'teacher' = full-model argmax "
                             "(default, maximises speculative acceptance). 'gt' = "
                             "dataset ground-truth next token (input_ids), so the "
                             "adapter learns the real answer directly. Requires "
                             "input_ids in the .ckpt (saved by generate_training_data*).")
    parser.add_argument("--prefix_ce_start", type=int, default=1,
                        help="Offset inside supervised answer positions for prefix CE. "
                             "Use 1 for speculative decoding because the first answer token is "
                             "generated by the full model for free, and the adapter's first real "
                             "draft predicts the second answer token. Use 0 for old behavior.")
    parser.add_argument("--prefix_ce_decay", type=float, default=1.0,
                        help="Geometric decay for prefix CE weights. 1.0 gives equal weights; "
                             "0.8 gives 1.0, 0.8, 0.64, ... across selected prefix tokens.")
    parser.add_argument("--min_mask_tokens", type=int, default=0,
                        help="Skip samples whose loss_mask.sum() <= this. "
                             "Set to 5 to drop NO REPLY samples (which have exactly 5 mask tokens).")
    parser.add_argument("--min_context_len", type=int, default=None,
                        help="Skip samples whose first supervised answer token starts before this index.")
    parser.add_argument("--max_context_len", type=int, default=None,
                        help="Skip samples whose first supervised answer token starts after this index.")
    parser.add_argument("--filter_cache", type=str, default=None,
                        help="Optional path to cache the filtered file list (avoid rescanning).")
    parser.add_argument("--init_from_base_layer", type=int, default=-1,
                        help="If >=0, initialize adapter weights from this layer of the base "
                             "model (also copies the final norm). EAGLE-style trick to inherit "
                             "long-context attention patterns from pretrained base. "
                             "-1 = disabled. Common choices: same as --exit_layer (e.g. 6), "
                             "or num_hidden_layers - 1 (last layer).")
    parser.add_argument("--val_ratio", type=float, default=0.05,
                        help="Fraction of data held out for validation (default 0.05 = 5%%). "
                             "Set to 0 to disable validation and train on all data (legacy mode).")
    parser.add_argument("--val_seed", type=int, default=42,
                        help="Seed for the deterministic train/val split. Same value + same "
                             "data list reproduces the same split across runs.")
    parser.add_argument("--val_subsample", type=int, default=0,
                        help="If > 0, evaluate at most this many val samples per epoch "
                             "(random subset). Useful when full val is slow. 0 = use all val.")
    return parser.parse_args()


def list_files(path):
    datapath = []
    for root, _, files in os.walk(path):
        for file in files:
            if file.endswith(".ckpt"):
                datapath.append(os.path.join(root, file))
    return sorted(datapath)


def _sample_lengths(path):
    data = torch.load(path, map_location="cpu", weights_only=False)
    loss_mask = data["loss_mask"].float()
    answer_positions = torch.nonzero(loss_mask > 0, as_tuple=False).flatten()
    answer_tokens = int(answer_positions.numel())
    context_len = int(answer_positions[0].item()) if answer_tokens > 0 else -1
    return context_len, answer_tokens


def filter_by_sample_metadata(
    files,
    min_mask_tokens=0,
    min_context_len=None,
    max_context_len=None,
    cache_path=None,
):
    """Keep files matching reply/context filters. Caches the result."""
    if min_mask_tokens <= 0 and min_context_len is None and max_context_len is None:
        return files

    if cache_path and os.path.exists(cache_path):
        with open(cache_path, "r") as f:
            cached = json.load(f)
        cache_matches = (
            cached.get("min_mask_tokens") == min_mask_tokens
            and cached.get("min_context_len") == min_context_len
            and cached.get("max_context_len") == max_context_len
            and set(cached.get("source_files", [])) == set(files)
        )
        if cache_matches:
            print(f"[filter] loaded {len(cached['kept_files'])} files from cache {cache_path}")
            return cached["kept_files"]

    kept = []
    print(
        f"[filter] scanning {len(files)} ckpts "
        f"(min_mask_tokens > {min_mask_tokens}, "
        f"min_context_len={min_context_len}, max_context_len={max_context_len})..."
    )
    for i, f in enumerate(files):
        try:
            context_len, answer_tokens = _sample_lengths(f)
        except Exception as e:
            print(f"  [skip] {f}: {e}")
            continue
        if answer_tokens <= min_mask_tokens:
            continue
        if min_context_len is not None and context_len < min_context_len:
            continue
        if max_context_len is not None and context_len > max_context_len:
            continue
        kept.append(f)
        if (i + 1) % 500 == 0:
            print(f"  scanned {i+1}/{len(files)}, kept {len(kept)}")
    print(f"[filter] kept {len(kept)}/{len(files)} ({100*len(kept)/max(len(files),1):.1f}%)")

    if cache_path:
        os.makedirs(os.path.dirname(cache_path) or ".", exist_ok=True)
        with open(cache_path, "w") as f:
            json.dump(
                {
                    "min_mask_tokens": min_mask_tokens,
                    "min_context_len": min_context_len,
                    "max_context_len": max_context_len,
                    "source_files": files,
                    "kept_files": kept,
                },
                f,
            )
        print(f"[filter] cached to {cache_path}")
    return kept


class AdapterDataset(Dataset):
    def __init__(self, datapath, exit_layer):
        self.data = datapath
        self.exit_layer = exit_layer

    def __len__(self):
        return len(self.data)

    def __getitem__(self, index):
        data = torch.load(self.data[index], map_location="cpu", weights_only=False)

        hidden_state = data["hidden_state"][None, :]
        loss_mask = data["loss_mask"]
        hidden_state_early = data[f"hidden_state_layer{self.exit_layer}"][None, :]

        orig_len = loss_mask.shape[0]
        loss_mask_shifted = torch.zeros(orig_len, dtype=torch.float32)
        if orig_len > 1:
            loss_mask_shifted[:orig_len - 1] = loss_mask[1:orig_len].float()

        # GT labels for direct-supervision CE: hidden_state at position i predicts
        # the token at position i+1, so the label at position i is input_ids[i+1].
        # Shift left by one to stay aligned with loss_mask_shifted; the trailing
        # slot is -100 (ignored by F.cross_entropy and never selected because
        # loss_mask is 0 there). Only used when --ce_target gt.
        input_ids = data.get("input_ids")
        if input_ids is not None:
            gt_labels = torch.full((orig_len,), -100, dtype=torch.long)
            if orig_len > 1:
                gt_labels[:orig_len - 1] = input_ids[1:orig_len].long()
            gt_labels = gt_labels.tolist()
        else:
            gt_labels = None

        length = hidden_state.shape[1]
        attention_mask = [1] * length

        # 3D mRoPE position_ids if saved (shape: (3, seq_len)). If absent,
        # adapter falls back to 1D arange (text-style T=H=W).
        position_ids = data.get("position_ids", None)
        if position_ids is not None:
            position_ids = position_ids[:, None, :]  # (3, 1, seq_len) — pseudo-batch dim

        return {
            "attention_mask": attention_mask,
            "loss_mask": loss_mask_shifted.tolist(),
            "gt_labels": gt_labels,
            "target": hidden_state,
            "hidden_state_big": hidden_state,
            "hidden_state_early": hidden_state_early,
            "position_ids": position_ids,
        }


class DataCollatorWithPadding:
    @staticmethod
    def paddingtensor(intensors, target_len):
        batch, cur_len, hidden = intensors.shape
        padding_tensor = torch.zeros(batch, target_len - cur_len, hidden, dtype=intensors.dtype)
        return torch.cat((intensors, padding_tensor), dim=1)

    @staticmethod
    def padding_position_ids(intensors, target_len):
        # intensors: (3, 1, seq_len)
        cur_len = intensors.shape[2]
        if cur_len >= target_len:
            return intensors
        padding = torch.zeros(3, 1, target_len - cur_len, dtype=intensors.dtype)
        return torch.cat((intensors, padding), dim=2)

    def __call__(self, features: List[Dict[str, Any]]) -> Dict[str, Any]:
        max_length = max(item["hidden_state_big"].shape[1] for item in features)
        out = {
            "hidden_states": torch.cat([self.paddingtensor(item["hidden_state_big"], max_length) for item in features]),
            "hidden_states_early": torch.cat([self.paddingtensor(item["hidden_state_early"], max_length) for item in features]),
            "target": torch.cat([self.paddingtensor(item["target"], max_length) for item in features]),
            "loss_mask": torch.tensor([item["loss_mask"] + [0] * (max_length - len(item["loss_mask"])) for item in features]),
            "attention_mask": torch.tensor([item["attention_mask"] + [0] * (max_length - len(item["attention_mask"])) for item in features]),
        }
        # Stack GT labels (-100 padded) if every sample carries them.
        if all(item.get("gt_labels") is not None for item in features):
            out["gt_labels"] = torch.tensor(
                [item["gt_labels"] + [-100] * (max_length - len(item["gt_labels"])) for item in features],
                dtype=torch.long,
            )
        else:
            out["gt_labels"] = None
        # Stack 3D position_ids if all features have them; else None.
        if all(f.get("position_ids") is not None for f in features):
            pos_padded = [self.padding_position_ids(f["position_ids"], max_length) for f in features]
            # Each is (3, 1, max_length); cat along batch dim → (3, B, max_length).
            out["position_ids"] = torch.cat(pos_padded, dim=1)
        else:
            out["position_ids"] = None
        return out


def save_adapter(model, adapter_config, args, accelerator, tag):
    """Save adapter weights and config to outdir/tag/."""
    unwrapped_model = accelerator.unwrap_model(model)
    save_dir = os.path.join(args.outdir, tag)
    os.makedirs(save_dir, exist_ok=True)
    torch.save(unwrapped_model.state_dict(), os.path.join(save_dir, "adapter_model.bin"))
    adapter_config_dict = {
        "hidden_size": adapter_config.hidden_size,
        "num_attention_heads": adapter_config.num_attention_heads,
        "num_key_value_heads": adapter_config.num_key_value_heads,
        "intermediate_size": adapter_config.intermediate_size,
        "num_hidden_layers": adapter_config.num_hidden_layers,
        "num_adapter_layers": getattr(adapter_config, "num_adapter_layers", 1),
        "rms_norm_eps": adapter_config.rms_norm_eps,
        "vocab_size": adapter_config.vocab_size,
        "max_position_embeddings": adapter_config.max_position_embeddings,
        "exit_layer": args.exit_layer,
        "use_mlp": getattr(adapter_config, "use_mlp", True),
        "loss": {
            "kl_temperature": args.kl_temperature,
            "prefix_ce_tokens": args.prefix_ce_tokens,
            "prefix_ce_weight": args.prefix_ce_weight,
            "prefix_ce_start": args.prefix_ce_start,
            "prefix_ce_decay": args.prefix_ce_decay,
            "ce_target": args.ce_target,
        },
    }
    with open(os.path.join(save_dir, "adapter_config.json"), "w") as f:
        json.dump(adapter_config_dict, f, indent=2)
    print(f"  Saved [{tag}] to {save_dir}")


def compute_kl_loss(out_head, target_head, loss_mask, temperature=1.0):
    """
    out_head:    [B, L, V] adapter logits
    target_head: [B, L, V] full-model logits (teacher)
    loss_mask:   [B, L, 1] (or [B, L])

    Memory-efficient: gather only the masked positions BEFORE running
    softmax/log_softmax. With sparse loss_mask (e.g. ShareGPT where only
    ~30% of tokens are assistant content), this avoids materialising
    [B, L, V] float32 softmax tensors over the whole sequence.
    """
    T = max(temperature, 1e-3)
    B, L, V = out_head.shape
    mask = loss_mask.squeeze(-1) if loss_mask.dim() == 3 else loss_mask  # [B, L]
    sel = mask > 0                                                         # [B, L] bool

    out_flat = out_head[sel]      # [N, V]   N = number of masked positions
    tgt_flat = target_head[sel]   # [N, V]
    w_flat = mask[sel]            # [N]

    if out_flat.shape[0] == 0:
        return out_head.sum() * 0.0  # keep graph alive but no loss

    target_p = F.softmax(tgt_flat / T, dim=-1).detach()
    out_logp = F.log_softmax(out_flat / T, dim=-1)
    per_token_kl = F.kl_div(out_logp, target_p, reduction="none").sum(dim=-1) * (T ** 2)
    return (per_token_kl * w_flat).sum() / w_flat.sum().clamp_min(1.0)


def build_prefix_weight_mask(loss_mask, prefix_tokens, prefix_start=0, decay=1.0):
    """Weight a prefix window inside EACH contiguous supervised segment.

    loss_mask: [B, L], already shifted to mark the answer tokens being predicted.
               Every contiguous run of (>0) values is treated as one assistant
               turn. Multi-turn ckpts (one ckpt per conversation) produce many
               such runs; the legacy per-turn ckpts produce exactly one.

    For each segment we skip `prefix_start` positions and weight the next
    `prefix_tokens` positions with geometric `decay`. This applies the
    speculative-decoding prefix-CE objective ("the first answer token of each
    turn is generated for free by verify; the adapter's first real draft
    predicts the second answer token") independently to every assistant turn.
    """
    prefix_weights = torch.zeros_like(loss_mask)
    if prefix_tokens <= 0:
        return prefix_weights

    prefix_start = max(0, prefix_start)
    decay = max(0.0, float(decay))

    for sample_idx in range(loss_mask.shape[0]):
        row = loss_mask[sample_idx]
        is_pos = (row > 0).to(torch.int8)
        if int(is_pos.sum().item()) == 0:
            continue

        padded = torch.cat([
            torch.zeros(1, dtype=torch.int8, device=is_pos.device),
            is_pos,
            torch.zeros(1, dtype=torch.int8, device=is_pos.device),
        ])
        diff = padded[1:] - padded[:-1]
        seg_starts = torch.nonzero(diff == 1, as_tuple=False).flatten().tolist()
        seg_ends = torch.nonzero(diff == -1, as_tuple=False).flatten().tolist()
        # seg_ends are exclusive (one past the last position in the segment).

        for seg_start, seg_end in zip(seg_starts, seg_ends):
            seg_len = seg_end - seg_start
            if prefix_start >= seg_len:
                continue
            take_start = seg_start + prefix_start
            take_end = min(seg_end, take_start + prefix_tokens)
            n = take_end - take_start
            if n <= 0:
                continue
            weights = decay ** torch.arange(
                n, device=loss_mask.device, dtype=loss_mask.dtype,
            )
            prefix_weights[sample_idx, take_start:take_end] = weights

    return prefix_weights


def compute_prefix_argmax_ce(
    out_head,
    target_head,
    loss_mask,
    prefix_tokens,
    prefix_start=0,
    prefix_decay=1.0,
    gt_labels=None,
):
    """Memory-efficient prefix CE: only compute CE at the weighted positions.

    The full [B, L] CE matrix can be tens of GB for big vocabulary + long
    sequences; instead we build the per-segment prefix-weight mask first,
    gather just the positions where the weight > 0, and compute CE only there.

    Label source:
      - gt_labels is None  -> teacher-argmax CE (fit the verify model's output;
                              maximises speculative acceptance rate).
      - gt_labels given     -> ground-truth CE (fit the dataset's real next
                              token). gt_labels: [B, L] long, already shifted so
                              position i holds input_ids[i+1], -100 elsewhere.
    """
    prefix_weights = build_prefix_weight_mask(
        loss_mask.squeeze(-1) if loss_mask.dim() == 3 else loss_mask,
        prefix_tokens,
        prefix_start=prefix_start,
        decay=prefix_decay,
    )                                                # [B, L]
    sel = prefix_weights > 0                         # [B, L] bool

    out_flat = out_head[sel]                          # [N, V]
    if out_flat.shape[0] == 0:
        return out_head.sum() * 0.0

    if gt_labels is not None:
        labels = gt_labels.to(out_flat.device)[sel].long()  # [N] real next tokens
    else:
        tgt_flat = target_head[sel]                   # [N, V]
        labels = tgt_flat.argmax(dim=-1).detach()     # [N] teacher argmax
    w_flat = prefix_weights[sel]                      # [N]

    per_token_ce = F.cross_entropy(out_flat, labels, reduction="none")  # [N]
    return (per_token_ce * w_flat).sum() / w_flat.sum().clamp_min(1.0)


def empty_match_stats():
    keys = [
        "token_correct", "token_total",
        "first_correct", "first_total",
        "draft1_correct", "draft1_total",
        "draft_prefix_correct", "draft_prefix_total",
        "long_token_correct", "long_token_total",
        "long_draft1_correct", "long_draft1_total",
        "long_draft_prefix_correct", "long_draft_prefix_total",
        "adapter_conf_sum", "teacher_conf_sum",
        "draft1_adapter_conf_sum", "draft1_teacher_conf_sum",
        "draft_prefix_adapter_conf_sum", "draft_prefix_teacher_conf_sum",
        "long_draft1_adapter_conf_sum", "long_draft1_teacher_conf_sum",
    ]
    return {key: 0.0 for key in keys}


def add_match_stats(total, stats):
    for key, value in stats.items():
        total[key] = total.get(key, 0.0) + float(value)


def safe_ratio(num, den):
    return float(num) / float(den) if den else 0.0


def match_acc(stats, name):
    return safe_ratio(stats.get(f"{name}_correct", 0.0), stats.get(f"{name}_total", 0.0))


def match_conf(stats, name, source="adapter"):
    return safe_ratio(stats.get(f"{name}_{source}_conf_sum", 0.0), stats.get(f"{name}_total", 0.0))


def gather_match_stats(accelerator, stats):
    keys = sorted(stats.keys())
    values = torch.tensor([stats.get(key, 0.0) for key in keys], device=accelerator.device)[None, :]
    gathered = accelerator.gather_for_metrics(values)
    summed = gathered.sum(dim=0)
    return {key: float(value.item()) for key, value in zip(keys, summed)}


@torch.no_grad()
def compute_match_stats(
    out_head,
    target_head,
    loss_mask,
    prob_exit=None,
    prob_target=None,
    draft_start=1,
    draft_prefix_tokens=1,
):
    """Exact top-1 metrics aligned with speculative decoding acceptance."""
    stats = empty_match_stats()
    mask = loss_mask.squeeze(-1).float() if loss_mask.dim() == 3 else loss_mask.float()

    pred = out_head.argmax(dim=-1)
    target = target_head.argmax(dim=-1)
    exact = pred.eq(target).float()

    if prob_exit is None:
        prob_exit = F.softmax(out_head.float(), dim=2)
    if prob_target is None:
        prob_target = F.softmax(target_head.float(), dim=2)
    adapter_conf = prob_exit.max(dim=2).values
    teacher_conf = prob_target.max(dim=2).values

    stats["token_correct"] = (exact * mask).sum().item()
    stats["token_total"] = mask.sum().item()
    stats["adapter_conf_sum"] = (adapter_conf * mask).sum().item()
    stats["teacher_conf_sum"] = (teacher_conf * mask).sum().item()

    draft_start = max(0, int(draft_start))
    draft_prefix_tokens = max(0, int(draft_prefix_tokens))

    for sample_idx in range(mask.shape[0]):
        valid_positions = torch.nonzero(mask[sample_idx] > 0, as_tuple=False).flatten()
        if valid_positions.numel() == 0:
            continue

        is_long = valid_positions.numel() > 5

        first_pos = valid_positions[0]
        stats["first_correct"] += exact[sample_idx, first_pos].item()
        stats["first_total"] += 1.0

        if is_long:
            stats["long_token_correct"] += exact[sample_idx, valid_positions].sum().item()
            stats["long_token_total"] += float(valid_positions.numel())

        if valid_positions.numel() > draft_start:
            draft1_pos = valid_positions[draft_start]
            stats["draft1_correct"] += exact[sample_idx, draft1_pos].item()
            stats["draft1_total"] += 1.0
            stats["draft1_adapter_conf_sum"] += adapter_conf[sample_idx, draft1_pos].item()
            stats["draft1_teacher_conf_sum"] += teacher_conf[sample_idx, draft1_pos].item()

            if is_long:
                stats["long_draft1_correct"] += exact[sample_idx, draft1_pos].item()
                stats["long_draft1_total"] += 1.0
                stats["long_draft1_adapter_conf_sum"] += adapter_conf[sample_idx, draft1_pos].item()
                stats["long_draft1_teacher_conf_sum"] += teacher_conf[sample_idx, draft1_pos].item()

        if draft_prefix_tokens > 0:
            prefix_positions = valid_positions[draft_start:draft_start + draft_prefix_tokens]
            if prefix_positions.numel() > 0:
                stats["draft_prefix_correct"] += exact[sample_idx, prefix_positions].sum().item()
                stats["draft_prefix_total"] += float(prefix_positions.numel())
                stats["draft_prefix_adapter_conf_sum"] += adapter_conf[sample_idx, prefix_positions].sum().item()
                stats["draft_prefix_teacher_conf_sum"] += teacher_conf[sample_idx, prefix_positions].sum().item()

                if is_long:
                    stats["long_draft_prefix_correct"] += exact[sample_idx, prefix_positions].sum().item()
                    stats["long_draft_prefix_total"] += float(prefix_positions.numel())

    return stats


@torch.no_grad()
def evaluate_on_loader(model, head, val_loader, accelerator, args):
    """One epoch of forward-only evaluation on the held-out set. Mirrors the
    training-loop metric collection so train and val numbers are directly
    comparable. No gradients, model put back into train mode on exit.
    """
    if val_loader is None:
        return None
    model.eval()
    total_loss = 0.0
    total_dist_overlap = 0.0
    n_batches = 0
    match_totals = empty_match_stats()

    for data in tqdm(val_loader, desc="[val]", leave=False):
        predict = model(
            inputs_embeds=data["hidden_states_early"],
            attention_mask=data["attention_mask"],
            position_ids=data.get("position_ids"),
        )
        target_head = head(data["target"].float())
        out_head = head(predict.float())
        prob_exit = F.softmax(out_head, dim=2)
        prob_target = F.softmax(target_head, dim=2)
        prob_acc_per_token = torch.min(prob_target, prob_exit).sum(dim=2)

        loss_mask = data["loss_mask"][:, :, None]
        if args.kl_weight > 0.0:
            kl_loss = compute_kl_loss(
                out_head=out_head, target_head=target_head,
                loss_mask=loss_mask, temperature=args.kl_temperature,
            )
        else:
            kl_loss = out_head.sum() * 0.0
        prefix_ce_loss = compute_prefix_argmax_ce(
            out_head=out_head, target_head=target_head, loss_mask=loss_mask,
            prefix_tokens=args.prefix_ce_tokens,
            prefix_start=args.prefix_ce_start,
            prefix_decay=args.prefix_ce_decay,
            gt_labels=data.get("gt_labels") if args.ce_target == "gt" else None,
        )
        loss = args.kl_weight * kl_loss + args.prefix_ce_weight * prefix_ce_loss
        dist_overlap = (data["loss_mask"] * prob_acc_per_token).sum() / data["loss_mask"].sum().clamp(min=1)

        batch_stats = compute_match_stats(
            out_head=out_head, target_head=target_head,
            loss_mask=data["loss_mask"],
            prob_exit=prob_exit, prob_target=prob_target,
            draft_start=1,
            draft_prefix_tokens=max(args.prefix_ce_tokens, 1),
        )
        add_match_stats(match_totals, batch_stats)
        total_loss += loss.item()
        total_dist_overlap += dist_overlap.item()
        n_batches += 1

    global_match = gather_match_stats(accelerator, match_totals)
    metrics = {
        'loss':         total_loss / max(n_batches, 1),
        'dist_overlap': total_dist_overlap / max(n_batches, 1),
        'top1':         match_acc(global_match, 'token'),
        'first':        match_acc(global_match, 'first'),
        'draft1':       match_acc(global_match, 'draft1'),
        'draftK':       match_acc(global_match, 'draft_prefix'),
        'long_top1':    match_acc(global_match, 'long_token'),
        'long_draft1':  match_acc(global_match, 'long_draft1'),
        'long_draftK':  match_acc(global_match, 'long_draft_prefix'),
        'dconf':        match_conf(global_match, 'draft1', 'adapter'),
        'tconf':        match_conf(global_match, 'draft1', 'teacher'),
        'long_dconf':   match_conf(global_match, 'long_draft1', 'adapter'),
        'n_batches':    n_batches,
    }
    model.train()
    return metrics


def compute_confidence_stats(prob_exit, loss_mask):
    max_conf_per_token = prob_exit.max(dim=2).values
    total_confidence = (max_conf_per_token * loss_mask).sum().item()
    total_tokens = loss_mask.sum().item()

    long_confidence = 0.0
    long_tokens = 0.0
    for sample_idx in range(loss_mask.shape[0]):
        sample_mask = loss_mask[sample_idx]
        sample_tokens = sample_mask.sum().item()
        if sample_tokens > 5:
            long_confidence += (max_conf_per_token[sample_idx] * sample_mask).sum().item()
            long_tokens += sample_tokens

    return total_confidence, total_tokens, long_confidence, long_tokens


def main():
    args = parse_args()

    torch.backends.cuda.matmul.allow_tf32 = True
    set_seed(0)

    ddp_kwargs = DistributedDataParallelKwargs(find_unused_parameters=True)
    accelerator = Accelerator(
        mixed_precision="bf16",
        gradient_accumulation_steps=args.gradient_accumulation_steps,
        kwargs_handlers=[ddp_kwargs],
    )

    try:
        from torch.utils.tensorboard import SummaryWriter
        writer = SummaryWriter(os.path.join(args.outdir, "tensorboard")) if accelerator.is_main_process else None
    except ImportError as e:
        writer = None
        if accelerator.is_main_process:
            print(f"[TensorBoard] disabled: {e}")
            print("Please install it with: pip install tensorboard")

    base_config = AutoConfig.from_pretrained(args.basepath)
    head = nn.Linear(base_config.hidden_size, base_config.vocab_size, bias=False)

    # Load lm_head in bf16 to halve its footprint (151k x 2k weight matrix is
    # ~1.2 GB in fp32 vs ~0.6 GB in bf16) and speed up matmul. The head is
    # frozen and only used for forward, so bf16 precision is plenty.
    head_dtype = torch.bfloat16
    try:
        from safetensors import safe_open

        index_path = os.path.join(args.basepath, "model.safetensors.index.json")
        with open(index_path, "r") as f:
            index_json = json.loads(f.read())
            head_path = index_json["weight_map"]["lm_head.weight"]
        with safe_open(os.path.join(args.basepath, head_path), framework="pt", device="cpu") as f:
            tensor_slice = f.get_slice("lm_head.weight")
            _, hidden_dim = tensor_slice.get_shape()
            tensor = tensor_slice[:, :hidden_dim].to(head_dtype)
    except Exception:
        try:
            index_path = os.path.join(args.basepath, "pytorch_model.bin.index.json")
            with open(index_path, "r") as f:
                index_json = json.loads(f.read())
                head_path = index_json["weight_map"]["lm_head.weight"]
            weights = torch.load(os.path.join(args.basepath, head_path), map_location="cpu")
            tensor = weights["lm_head.weight"].to(head_dtype)
        except Exception:
            model_path = os.path.join(args.basepath, "model.safetensors")
            if os.path.exists(model_path):
                from safetensors import safe_open
                with safe_open(model_path, framework="pt", device="cpu") as f:
                    tensor = f.get_tensor("lm_head.weight").to(head_dtype)
            else:
                raise RuntimeError(f"Cannot find lm_head weights in {args.basepath}")

    head.weight.data = tensor
    head.to(head_dtype)
    head.eval()
    for param in head.parameters():
        param.requires_grad = False

    datapath = list_files(args.datadir)
    if not datapath:
        raise ValueError(f"No .ckpt files found in {args.datadir}")

    datapath = filter_by_sample_metadata(
        datapath,
        min_mask_tokens=args.min_mask_tokens,
        min_context_len=args.min_context_len,
        max_context_len=args.max_context_len,
        cache_path=args.filter_cache,
    )
    if not datapath:
        raise ValueError(
            f"No samples left after filter "
            f"(min_mask_tokens={args.min_mask_tokens}, "
            f"min_context_len={args.min_context_len}, max_context_len={args.max_context_len})"
        )

    # Deterministic train/val split. Same args.val_seed + same datapath list
    # produces the same split across runs, so resuming sees the same val set.
    import random as _random
    _shuffled = sorted(datapath)
    _rng = _random.Random(args.val_seed)
    _rng.shuffle(_shuffled)
    if args.val_ratio > 0:
        n_val = max(1, int(len(_shuffled) * args.val_ratio))
        val_paths = _shuffled[:n_val]
        train_paths = _shuffled[n_val:]
        # Optional cap on val set size for fast per-epoch eval.
        if args.val_subsample > 0 and len(val_paths) > args.val_subsample:
            val_paths = val_paths[:args.val_subsample]
    else:
        val_paths = []
        train_paths = _shuffled

    if accelerator.is_main_process:
        print(f"Train: {len(train_paths)} samples")
        print(f"Val:   {len(val_paths)} samples"
              f" (val_ratio={args.val_ratio}, seed={args.val_seed}"
              f"{', subsample=' + str(args.val_subsample) if args.val_subsample else ''})")

    traindataset = AdapterDataset(train_paths, args.exit_layer)

    train_loader = DataLoader(
        traindataset,
        batch_size=args.bs,
        shuffle=True,
        collate_fn=DataCollatorWithPadding(),
        # 2 workers + pin_memory is a CPU-light setup that still hides most
        # of the per-batch IO latency behind GPU compute. Bumping num_workers
        # higher gives diminishing returns and competes with other users on
        # shared CPU.
        num_workers=2,
        pin_memory=True,
    )

    if val_paths:
        valdataset = AdapterDataset(val_paths, args.exit_layer)
        val_loader = DataLoader(
            valdataset,
            batch_size=args.bs,
            shuffle=False,
            collate_fn=DataCollatorWithPadding(),
            num_workers=2,
            pin_memory=True,
        )
    else:
        val_loader = None

    if accelerator.is_main_process:
        os.makedirs(args.outdir, exist_ok=True)

    adapter_config = create_adapter_config(args.basepath, num_adapter_layers=args.num_adapter_layers)
    adapter_config.use_mlp = not args.disable_adapter_mlp
    model = AdapterModel(adapter_config)
    if accelerator.is_main_process:
        print(f"Adapter config: use_mlp={getattr(adapter_config, 'use_mlp', True)}, "
              f"num_adapter_layers={args.num_adapter_layers}")
        print(model)

    if not args.resume_adapter:
        # All processes must initialize the same weights (called pre-DDP-prepare).
        source_layer = args.init_from_base_layer if args.init_from_base_layer >= 0 else args.exit_layer
        init_adapter_from_base_layer(model, args.basepath, source_layer)

    if args.resume_adapter:
        state_dict = torch.load(args.resume_adapter, map_location="cpu")
        missing, unexpected = model.load_state_dict(state_dict, strict=False)
        if missing:
            print(f"[resume] WARNING: {len(missing)} missing keys (e.g. {missing[:3]}). "
                  f"These will keep their freshly-initialized values from init_adapter_from_base_layer or random.")
        if unexpected:
            print(f"[resume] WARNING: {len(unexpected)} unexpected keys (e.g. {unexpected[:3]}). "
                  f"These will be dropped silently.")
        print(f"Loaded pretrained adapter from {args.resume_adapter}")
        if args.init_from_base_layer >= 0:
            print(f"  (note: --init_from_base_layer was set but ignored because --resume_adapter takes precedence)")

    optimizer = optim.AdamW(model.parameters(), lr=args.lr, betas=(0.9, 0.95))
    model, head, optimizer, train_loader = accelerator.prepare(
        model, head, optimizer, train_loader
    )
    if val_loader is not None:
        val_loader = accelerator.prepare(val_loader)

    updates_per_epoch = max(1, (len(train_loader) + args.gradient_accumulation_steps - 1) // args.gradient_accumulation_steps)
    total_training_steps = args.total_steps if args.total_steps > 0 else updates_per_epoch * args.num_epochs
    warmup_steps = min(args.num_warmup_steps, max(total_training_steps - 1, 0))
    scheduler = get_linear_schedule_with_warmup(
        optimizer,
        num_warmup_steps=warmup_steps,
        num_training_steps=max(total_training_steps, 1),
    )
    scheduler = accelerator.prepare(scheduler)

    if accelerator.is_main_process:
        effective_bs = args.bs * args.gradient_accumulation_steps * accelerator.num_processes
        print(f"Effective batch size: {effective_bs}")
        print(f"Updates per epoch: {updates_per_epoch}")
        print(f"Total optimizer steps: {total_training_steps}")
        print(f"Warmup steps: {warmup_steps}")
        print("Note: scheduler steps are optimizer-update steps, not dataloader batch steps.")
        print(
            f"Loss: KL(T={args.kl_temperature})"
            f" + {args.prefix_ce_weight} * WeightedPrefixCE("
            f"target={args.ce_target}, start={args.prefix_ce_start}, "
            f"tokens={args.prefix_ce_tokens}, decay={args.prefix_ce_decay})"
        )

    if args.start_epoch > 0 and not args.resume_adapter:
        state_dir = os.path.join(args.outdir, "state", f"state_{args.start_epoch - 1}")
        if os.path.exists(state_dir):
            accelerator.load_state(state_dir)
            print(f"Resumed from {state_dir}")

    for epoch in range(args.start_epoch, args.start_epoch + args.num_epochs):
        print(f"=== Epoch {epoch} ===")
        epoch_loss = 0.0
        epoch_dist_overlap = 0.0
        num_batches = 0
        nan_detected = False
        match_totals = empty_match_stats()
        optimizer_updates = 0
        model.train()
        optimizer.zero_grad(set_to_none=True)

        for batch_idx, data in enumerate(tqdm(train_loader)):
            with accelerator.accumulate(model):
                if args.ce_target == "gt" and data.get("gt_labels") is None:
                    raise ValueError(
                        "--ce_target gt requires 'input_ids' in every .ckpt, but a "
                        "batch had none. Regenerate data with generate_training_data*.py "
                        "(it saves input_ids) or use --ce_target teacher."
                    )
                predict = model(
                    inputs_embeds=data["hidden_states_early"],
                    attention_mask=data["attention_mask"],
                    position_ids=data.get("position_ids"),
                )

                with torch.no_grad():
                    target_head = head(data["target"].float())

                out_head = head(predict.float())
                prob_exit = F.softmax(out_head, dim=2)
                prob_last = F.softmax(target_head, dim=2)
                prob_acc_per_token = torch.min(prob_last, prob_exit).sum(dim=2)

                loss_mask = data["loss_mask"][:, :, None]
                if args.kl_weight > 0.0:
                    kl_loss = compute_kl_loss(
                        out_head=out_head,
                        target_head=target_head,
                        loss_mask=loss_mask,
                        temperature=args.kl_temperature,
                    )
                else:
                    # Skip KL entirely (faster, less GPU mem). Keep a 0-tensor
                    # for logging so downstream prints don't break.
                    kl_loss = out_head.sum() * 0.0
                prefix_ce_loss = compute_prefix_argmax_ce(
                    out_head=out_head,
                    target_head=target_head,
                    loss_mask=loss_mask,
                    prefix_tokens=args.prefix_ce_tokens,
                    prefix_start=args.prefix_ce_start,
                    prefix_decay=args.prefix_ce_decay,
                    gt_labels=data.get("gt_labels") if args.ce_target == "gt" else None,
                )
                loss = args.kl_weight * kl_loss + args.prefix_ce_weight * prefix_ce_loss

                dist_overlap = torch.sum(data["loss_mask"] * prob_acc_per_token) / data["loss_mask"].sum().clamp(min=1)

                with torch.no_grad():
                    batch_stats = compute_match_stats(
                        out_head=out_head,
                        target_head=target_head,
                        loss_mask=data["loss_mask"],
                        prob_exit=prob_exit,
                        prob_target=prob_last,
                        draft_start=1,
                        draft_prefix_tokens=max(args.prefix_ce_tokens, 1),
                    )

                nan_flag = torch.tensor(
                    1.0 if (torch.isnan(loss) or torch.isinf(loss)) else 0.0,
                    device=accelerator.device,
                )
                nan_flag = accelerator.reduce(nan_flag, reduction="sum")
                if nan_flag.item() > 0:
                    if accelerator.is_main_process:
                        print(f"\nNaN/Inf loss at epoch {epoch}, batch {batch_idx} - skipping")
                    nan_detected = True
                    optimizer.zero_grad(set_to_none=True)
                    continue

                if accelerator.is_main_process and batch_idx % args.log_steps == 0:
                    current_lr = optimizer.optimizer.param_groups[0]["lr"]
                    print(
                        f"\nStep: {batch_idx}"
                        f"\tOptStep: {optimizer_updates}"
                        f"\tLR: {current_lr:.3e}"
                        f"\tLoss: {loss.item():.4f}"
                        f"\tKL: {kl_loss.item():.4f}"
                        f"\tWPrefixCE: {prefix_ce_loss.item():.4f}"
                        f"\tTop1: {match_acc(batch_stats, 'token'):.4f}"
                        f"\tFirst: {match_acc(batch_stats, 'first'):.4f}"
                        f"\tDraft1: {match_acc(batch_stats, 'draft1'):.4f}"
                        f"\tDraftK: {match_acc(batch_stats, 'draft_prefix'):.4f}"
                        f"\tLongDraft1: {match_acc(batch_stats, 'long_draft1'):.4f}"
                        f"\tDConf: {match_conf(batch_stats, 'draft1', 'adapter'):.4f}"
                        f"\tTConf: {match_conf(batch_stats, 'draft1', 'teacher'):.4f}"
                        f"\tDistOverlap: {dist_overlap.item():.4f}"
                    )

                accelerator.backward(loss)
                if accelerator.sync_gradients:
                    accelerator.clip_grad_value_(model.parameters(), args.grad_clip)
                    optimizer.step()
                    scheduler.step()
                    optimizer.zero_grad(set_to_none=True)
                    optimizer_updates += 1

            add_match_stats(match_totals, batch_stats)

            if accelerator.is_main_process and writer is not None and batch_stats.get("token_total", 0.0) != 0:
                global_step = batch_idx + len(train_loader) * epoch
                writer.add_scalar("train/lr", optimizer.optimizer.param_groups[0]["lr"], global_step)
                writer.add_scalar("train/loss", loss.item(), global_step)
                writer.add_scalar("train/kl_loss", kl_loss.item(), global_step)
                writer.add_scalar("train/weighted_prefix_ce_loss", prefix_ce_loss.item(), global_step)
                writer.add_scalar("train/dist_overlap", dist_overlap.item(), global_step)
                writer.add_scalar("train/top1_acc", match_acc(batch_stats, "token"), global_step)
                writer.add_scalar("train/free_first_acc", match_acc(batch_stats, "first"), global_step)
                writer.add_scalar("train/draft1_acc", match_acc(batch_stats, "draft1"), global_step)
                writer.add_scalar("train/draft_prefix_acc", match_acc(batch_stats, "draft_prefix"), global_step)
                writer.add_scalar("train/long_draft1_acc", match_acc(batch_stats, "long_draft1"), global_step)
                writer.add_scalar("train/draft1_adapter_conf", match_conf(batch_stats, "draft1", "adapter"), global_step)
                writer.add_scalar("train/draft1_teacher_conf", match_conf(batch_stats, "draft1", "teacher"), global_step)

            epoch_loss += loss.item()
            epoch_dist_overlap += dist_overlap.item()
            num_batches += 1

        global_match_stats = gather_match_stats(accelerator, match_totals)

        epoch_loss /= max(num_batches, 1)
        epoch_dist_overlap /= max(num_batches, 1)
        epoch_acc = match_acc(global_match_stats, "token")
        epoch_first_acc = match_acc(global_match_stats, "first")
        epoch_draft1_acc = match_acc(global_match_stats, "draft1")
        epoch_draft_prefix_acc = match_acc(global_match_stats, "draft_prefix")
        epoch_long_acc = match_acc(global_match_stats, "long_token")
        epoch_long_draft1_acc = match_acc(global_match_stats, "long_draft1")
        epoch_long_draft_prefix_acc = match_acc(global_match_stats, "long_draft_prefix")
        epoch_confidence = safe_ratio(
            global_match_stats.get("adapter_conf_sum", 0.0),
            global_match_stats.get("token_total", 0.0),
        )
        epoch_draft1_confidence = match_conf(global_match_stats, "draft1", "adapter")
        epoch_draft1_teacher_confidence = match_conf(global_match_stats, "draft1", "teacher")
        epoch_long_draft1_confidence = match_conf(global_match_stats, "long_draft1", "adapter")

        # ---- Validation pass (no gradients) ----
        val_metrics = evaluate_on_loader(model, head, val_loader, accelerator, args)

        if accelerator.is_main_process:
            print(
                f"Train [{epoch + 1}/{args.num_epochs}]"
                f"  Loss: {epoch_loss:.4f}"
                f"  Top1: {100 * epoch_acc:.2f}%"
                f"  First(free): {100 * epoch_first_acc:.2f}%"
                f"  Draft1: {100 * epoch_draft1_acc:.2f}%"
                f"  DraftK: {100 * epoch_draft_prefix_acc:.2f}%"
                f"  LongTop1: {100 * epoch_long_acc:.2f}%"
                f"  LongDraft1: {100 * epoch_long_draft1_acc:.2f}%"
                f"  LongDraftK: {100 * epoch_long_draft_prefix_acc:.2f}%"
                f"  DConf: {epoch_draft1_confidence:.4f}"
                f"  TConf: {epoch_draft1_teacher_confidence:.4f}"
                f"  LongDConf: {epoch_long_draft1_confidence:.4f}"
                f"  DistOverlap: {epoch_dist_overlap:.4f}"
            )
            if val_metrics is not None:
                print(
                    f"Val   [{epoch + 1}/{args.num_epochs}]"
                    f"  Loss: {val_metrics['loss']:.4f}"
                    f"  Top1: {100 * val_metrics['top1']:.2f}%"
                    f"  First(free): {100 * val_metrics['first']:.2f}%"
                    f"  Draft1: {100 * val_metrics['draft1']:.2f}%"
                    f"  DraftK: {100 * val_metrics['draftK']:.2f}%"
                    f"  LongTop1: {100 * val_metrics['long_top1']:.2f}%"
                    f"  LongDraft1: {100 * val_metrics['long_draft1']:.2f}%"
                    f"  LongDraftK: {100 * val_metrics['long_draftK']:.2f}%"
                    f"  DConf: {val_metrics['dconf']:.4f}"
                    f"  TConf: {val_metrics['tconf']:.4f}"
                    f"  LongDConf: {val_metrics['long_dconf']:.4f}"
                    f"  DistOverlap: {val_metrics['dist_overlap']:.4f}"
                )
            if nan_detected:
                print("  Some NaN batches were skipped")

            # Use VAL metrics for ckpt name if we have a val set, train metrics otherwise.
            if val_metrics is not None:
                tag_prefix = "val"
                tag_top1 = val_metrics['top1']
                tag_draft1 = val_metrics['draft1']
                tag_long_draft1 = val_metrics['long_draft1']
                tag_overlap = val_metrics['dist_overlap']
                tag_loss = val_metrics['loss']
            else:
                tag_prefix = "train"
                tag_top1 = epoch_acc
                tag_draft1 = epoch_draft1_acc
                tag_long_draft1 = epoch_long_draft1_acc
                tag_overlap = epoch_dist_overlap
                tag_loss = epoch_loss

            epoch_tag = (
                f"epochs/"
                f"epoch{epoch:03d}"
                f"_{tag_prefix}top1{tag_top1:.4f}"
                f"_{tag_prefix}draft1{tag_draft1:.4f}"
                f"_{tag_prefix}longdraft1{tag_long_draft1:.4f}"
                f"_{tag_prefix}overlap{tag_overlap:.4f}"
                f"_{tag_prefix}loss{tag_loss:.4f}"
            )
            save_adapter(model, adapter_config, args, accelerator, epoch_tag)

            if writer is not None:
                writer.add_scalar("train/loss", epoch_loss, epoch)
                writer.add_scalar("train/top1_acc", epoch_acc, epoch)
                writer.add_scalar("train/free_first_acc", epoch_first_acc, epoch)
                writer.add_scalar("train/draft1_acc", epoch_draft1_acc, epoch)
                writer.add_scalar("train/draft_prefix_acc", epoch_draft_prefix_acc, epoch)
                writer.add_scalar("train/long_top1_acc", epoch_long_acc, epoch)
                writer.add_scalar("train/long_draft1_acc", epoch_long_draft1_acc, epoch)
                writer.add_scalar("train/long_draft_prefix_acc", epoch_long_draft_prefix_acc, epoch)
                writer.add_scalar("train/dist_overlap", epoch_dist_overlap, epoch)
                writer.add_scalar("train/confidence", epoch_confidence, epoch)
                writer.add_scalar("train/draft1_adapter_confidence", epoch_draft1_confidence, epoch)
                writer.add_scalar("train/draft1_teacher_confidence", epoch_draft1_teacher_confidence, epoch)
                writer.add_scalar("train/long_draft1_adapter_confidence", epoch_long_draft1_confidence, epoch)
                if val_metrics is not None:
                    writer.add_scalar("val/loss", val_metrics['loss'], epoch)
                    writer.add_scalar("val/top1_acc", val_metrics['top1'], epoch)
                    writer.add_scalar("val/free_first_acc", val_metrics['first'], epoch)
                    writer.add_scalar("val/draft1_acc", val_metrics['draft1'], epoch)
                    writer.add_scalar("val/draft_prefix_acc", val_metrics['draftK'], epoch)
                    writer.add_scalar("val/long_top1_acc", val_metrics['long_top1'], epoch)
                    writer.add_scalar("val/long_draft1_acc", val_metrics['long_draft1'], epoch)
                    writer.add_scalar("val/long_draft_prefix_acc", val_metrics['long_draftK'], epoch)
                    writer.add_scalar("val/dist_overlap", val_metrics['dist_overlap'], epoch)
                    writer.add_scalar("val/draft1_adapter_confidence", val_metrics['dconf'], epoch)
                    writer.add_scalar("val/draft1_teacher_confidence", val_metrics['tconf'], epoch)
                    writer.add_scalar("val/long_draft1_adapter_confidence", val_metrics['long_dconf'], epoch)

        if epoch % args.save_freq == 0 or epoch == args.start_epoch + args.num_epochs - 1:
            accelerator.save_state(output_dir=os.path.join(args.outdir, "state", f"state_{epoch}"))
            if accelerator.is_main_process:
                print(f"  Saved full state for epoch {epoch}")

    if accelerator.is_main_process and writer is not None:
        writer.close()

    print("Training complete!")


if __name__ == "__main__":
    main()